# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: l12s
description: 
tagline: 
url: l12s.com

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: .build
# Exclude the js and sass directories, as they get created via separate gulp processes
exclude: [assets/js/, assets/sass/]

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: Leah Jones
  email: leah@l12s.com
  bio: 
  twitter: l12s_
  linkedin: leahjonesresume
  github: l12s

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

future: false
show_drafts: false
lsi: true
limit_posts: 0

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 10
paginate_path: '/blog/page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true
